# Deep GCN Model configuration
in_channels: 3
hidden_channels: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128]
out_channels: 2
conv_types: ["GEN", "GEN","GEN", "GEN","GEN", "GEN","GEN", "GEN","GEN", "GEN"]
final_layer_type: "Linear"
activation: "relu"
dropout: 0.1
block: "plain" # works only plain, the other stucks (dense makes dimensional issues, res and res+ explode)
use_bn: true
gat_heads: 4
cheb_K: 3
residual: false  # works only false
