# Deep GCN Model configuration
in_channels: 3
hidden_channels: [32, 32, 32]
out_channels: 2
conv_types: ["GCN", "GCN", "GCN"]
final_layer_type: "Linear"
activation: "tanh"
dropout: 0.1
block: "plain"
use_bn: true
gat_heads: 4
cheb_K: 3
