# Dataset configuration - Fast training profile
# HDF5 precomputed dataset path
h5_path: "data/simulations.h5"

# Sampling configuration (reduced for fast experimentation)
num_samples: 10         # Number of simulations to load from HDF5
num_timesteps: 50       # Number of timesteps per simulation to use
window_length: 20       # Timesteps per random window sample

# Training split
train_ratio: 0.8
batch_size: 4
shuffle: true
drop_last: false

# Legacy parameters (kept for compatibility)
num_graphs: 100
dt: 0.1

# Physics parameters
wave_speed: 1.0  # c
damping: 1.0     # k

# Mesh parameters
num_nodes: 100
domain_length: 1.0

# Force parameters
force:
  margin: 0.1
  sign: -1.0
  location: "casual"  # "casual" or fixed coordinates
  forcing_type: "middle"  # "casual", "start", "middle", "end". NOT IMPLEMENTED YET

# Data scaling
scaling:
  enabled: false
  method: "standard"  # "standard" (z-score) or "minmax"
  per_feature: true   # Scale each feature independently
  epsilon: 1.0e-8     # Small value to prevent division by zero
