# Dataset configuration
# HDF5 precomputed dataset path
h5_path: "data/simulations.h5"

# Sampling configuration
num_samples: 100        # Number of simulations to load from HDF5
num_timesteps: 200      # Number of timesteps per simulation to use
window_length: 200      # Timesteps per random window sample (should match num_timesteps)

# Training split
train_ratio: 0.8
batch_size: 4
shuffle: true
drop_last: false

# Legacy parameters (kept for compatibility, not used with HDF5)
num_graphs: 5000
num_steps: 6
dt: 0.01

# Physics parameters
wave_speed: 1.0  # c
damping: 1.0     # k

# Mesh parameters
num_nodes: 100
domain_length: 1.0

# Force parameters
force:
  margin: 0.1
  sign: -1.0
  location: "casual"  # "casual" or fixed coordinates
  forcing_type: "middle"  # "casual", "start", "middle", "end". NOT IMPLEMENTED YET

# Data scaling
scaling:
  enabled: false
  method: "standard"  # "standard" (z-score) or "minmax"
  per_feature: true   # Scale each feature independently
  epsilon: 1.0e-8     # Small value to prevent division by zero
