# Training configuration with adaptive loss weighting (EMA strategy)
# This config equalizes losses at epoch 1, then continuously adapts using exponential moving average

epochs: 50
learning_rate: 0.005
weight_decay: 1.0e-5
optimizer: "adam"

# Loss weights (will be adjusted by adaptive weighting)
loss:
  w1_PI: 1.0  # Initial weight for displacement loss
  w2_PI: 1.0  # Initial weight for velocity loss
  use_rk4: true
  w1_rk4: 1.0  # Initial weight for RK4 displacement loss
  w2_rk4: 1.0  # Initial weight for RK4 velocity loss
  use_gn_solver: false
  
  # Adaptive loss weighting - ENABLED with EMA
  adaptive:
    enabled: true
    strategy: "equal_init_ema"  # Equalize at epoch 1, then adapt with EMA
    ema_alpha: 0.9  # 90% old value, 10% new value
    update_frequency: 1  # Update every epoch

# Logging
log_interval: 5
save_best: true
checkpoint_path: "best_model.pt"

# Early stopping
early_stopping:
  enabled: false
  patience: 10
  min_delta: 1.0e-6
