# Training configuration
epochs: 50
learning_rate: 0.005
weight_decay: 1.0e-5
optimizer: "adam"  # "adam", "sgd", etc.

# Loss weights
loss:
  w1_PI: 1.649e+00  # weight for displacement loss
  w2_PI: 5.531e+00  # weight for velocity loss
  use_rk4: true
  w1_rk4: 1.651e+00
  w2_rk4: 1.470e-01
  use_gn_solver: false
  
  # Adaptive loss weighting
  adaptive:
    enabled: true  # Enable adaptive weighting
    strategy: "ema"  # Options: 'equal_init', 'equal_init_ema', 'ema', 'fixed'
    ema_alpha: 0.8  # Exponential moving average coefficient (0.8 = 80% old, 20% new)
    update_frequency: 1  # Update weights every N epochs
    # Strategy descriptions:
    # - 'equal_init': Equalize all losses at epoch 1, then keep fixed
    # - 'equal_init_ema': Equalize at epoch 1, then adapt with EMA
    # - 'ema': Always use EMA (no initial equalization)
    # - 'fixed': Use fixed weights from config (no adaptation)

# Logging
log_interval: 5  # log every N epochs
save_best: true
checkpoint_path: "best_model.pt"

# Early stopping
early_stopping:
  enabled: true
  patience: 10
  min_delta: 1.0e-6
