# Fast training configuration (for testing)
epochs: 10
learning_rate: 0.01
weight_decay: 1.0e-5
optimizer: "adam"

# Loss weights
loss:
  w1: 1.0
  w2: 1.0
  use_rk4: false
  use_gn_solver: true

# Logging
log_interval: 2
save_best: true
checkpoint_path: "best_model.pt"

# Early stopping
early_stopping:
  enabled: false
  patience: 5
  min_delta: 1.0e-6
