# Main configuration file
defaults:
  - dataset: fast_dataset
  - model: fast_model
  - training: fast_training
  - _self_

# Experiment settings
experiment:
  name: "gcn_string_wave"
  seed: 42
  device: "cuda"  # "cuda" or "cpu"
  output_dir: "./outputs"
  save_dir: "./checkpoints"

# Hydra settings
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Run settings
run:
  train: True
  plot_dataset: True

